# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b9741f5461ff3137d3c97601e368a176f8a1fc5d402713e6f955c06118b246cf87255f879419fb45b13bdd446efadad3db747207f27f08487c6747c4021eda

test:
  secret_key_base: 91bc28d8663bc1106ca99d327cda0093ac7ea7fb738381a11da6eb8002c296947943fc9ddeafc4648a9bbf99556b5245ad08900c23e9532e0f5d424fd28632d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
